name: folder_1_action

# on: [push] 
#   paths: 
#     - "folder_1"

on:
  push:
    branches:
      - 'releases/**'
      - '!releases/**-alpha'

jobs: 
  check-bats-version: 
    runs-on: ubuntu-latest 
    steps: 
      - run: echo "running some github action job for folder 1"